// ========================================================================================
// THIS FILE HAS BEEN AUTOGENERATED - Do not edit directly
// ----------------------------------------------------------------------------------------
// Edit the template at 'scripts/rust_generator/templates/array_binary_operations.rs' instead
// ========================================================================================

use crate::datatypes::*;

// =========================================
// Real numbers
// =========================================

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// ADD for 1D arrays and scalars
#[rustler::nif]
pub fn float64_add_array1_array1(a: ExFloat64Array1, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array1_scalar(a: ExFloat64Array1, b: f64) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array1(a: f64, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(a + &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// ADD for 2D arrays and scalars
#[rustler::nif]
pub fn float64_add_array2_array2(a: ExFloat64Array2, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array2_scalar(a: ExFloat64Array2, b: f64) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array2(a: f64, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(a + &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// ADD for 3D arrays and scalars
#[rustler::nif]
pub fn float64_add_array3_array3(a: ExFloat64Array3, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array3_scalar(a: ExFloat64Array3, b: f64) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array3(a: f64, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(a + &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// ADD for 4D arrays and scalars
#[rustler::nif]
pub fn float64_add_array4_array4(a: ExFloat64Array4, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array4_scalar(a: ExFloat64Array4, b: f64) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array4(a: f64, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(a + &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// ADD for 5D arrays and scalars
#[rustler::nif]
pub fn float64_add_array5_array5(a: ExFloat64Array5, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array5_scalar(a: ExFloat64Array5, b: f64) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array5(a: f64, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(a + &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// ADD for 6D arrays and scalars
#[rustler::nif]
pub fn float64_add_array6_array6(a: ExFloat64Array6, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float64_add_array6_scalar(a: ExFloat64Array6, b: f64) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float64_add_scalar_array6(a: f64, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(a + &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// SUBTRACT for 1D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array1_array1(a: ExFloat64Array1, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array1_scalar(a: ExFloat64Array1, b: f64) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array1(a: f64, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(a - &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// SUBTRACT for 2D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array2_array2(a: ExFloat64Array2, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array2_scalar(a: ExFloat64Array2, b: f64) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array2(a: f64, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(a - &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// SUBTRACT for 3D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array3_array3(a: ExFloat64Array3, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array3_scalar(a: ExFloat64Array3, b: f64) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array3(a: f64, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(a - &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// SUBTRACT for 4D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array4_array4(a: ExFloat64Array4, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array4_scalar(a: ExFloat64Array4, b: f64) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array4(a: f64, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(a - &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// SUBTRACT for 5D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array5_array5(a: ExFloat64Array5, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array5_scalar(a: ExFloat64Array5, b: f64) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array5(a: f64, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(a - &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// SUBTRACT for 6D arrays and scalars
#[rustler::nif]
pub fn float64_subtract_array6_array6(a: ExFloat64Array6, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float64_subtract_array6_scalar(a: ExFloat64Array6, b: f64) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float64_subtract_scalar_array6(a: f64, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(a - &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// MULTIPLY for 1D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array1_array1(a: ExFloat64Array1, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array1_scalar(a: ExFloat64Array1, b: f64) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array1(a: f64, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(a * &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// MULTIPLY for 2D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array2_array2(a: ExFloat64Array2, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array2_scalar(a: ExFloat64Array2, b: f64) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array2(a: f64, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(a * &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// MULTIPLY for 3D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array3_array3(a: ExFloat64Array3, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array3_scalar(a: ExFloat64Array3, b: f64) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array3(a: f64, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(a * &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// MULTIPLY for 4D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array4_array4(a: ExFloat64Array4, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array4_scalar(a: ExFloat64Array4, b: f64) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array4(a: f64, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(a * &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// MULTIPLY for 5D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array5_array5(a: ExFloat64Array5, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array5_scalar(a: ExFloat64Array5, b: f64) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array5(a: f64, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(a * &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// MULTIPLY for 6D arrays and scalars
#[rustler::nif]
pub fn float64_multiply_array6_array6(a: ExFloat64Array6, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float64_multiply_array6_scalar(a: ExFloat64Array6, b: f64) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float64_multiply_scalar_array6(a: f64, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(a * &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// DIVIDE for 1D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array1_array1(a: ExFloat64Array1, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array1_scalar(a: ExFloat64Array1, b: f64) -> ExFloat64Array1 {
  ExFloat64Array1::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array1(a: f64, b: ExFloat64Array1) -> ExFloat64Array1 {
  ExFloat64Array1::new(a / &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// DIVIDE for 2D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array2_array2(a: ExFloat64Array2, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array2_scalar(a: ExFloat64Array2, b: f64) -> ExFloat64Array2 {
  ExFloat64Array2::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array2(a: f64, b: ExFloat64Array2) -> ExFloat64Array2 {
  ExFloat64Array2::new(a / &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// DIVIDE for 3D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array3_array3(a: ExFloat64Array3, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array3_scalar(a: ExFloat64Array3, b: f64) -> ExFloat64Array3 {
  ExFloat64Array3::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array3(a: f64, b: ExFloat64Array3) -> ExFloat64Array3 {
  ExFloat64Array3::new(a / &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// DIVIDE for 4D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array4_array4(a: ExFloat64Array4, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array4_scalar(a: ExFloat64Array4, b: f64) -> ExFloat64Array4 {
  ExFloat64Array4::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array4(a: f64, b: ExFloat64Array4) -> ExFloat64Array4 {
  ExFloat64Array4::new(a / &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// DIVIDE for 5D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array5_array5(a: ExFloat64Array5, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array5_scalar(a: ExFloat64Array5, b: f64) -> ExFloat64Array5 {
  ExFloat64Array5::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array5(a: f64, b: ExFloat64Array5) -> ExFloat64Array5 {
  ExFloat64Array5::new(a / &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// DIVIDE for 6D arrays and scalars
#[rustler::nif]
pub fn float64_divide_array6_array6(a: ExFloat64Array6, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float64_divide_array6_scalar(a: ExFloat64Array6, b: f64) -> ExFloat64Array6 {
  ExFloat64Array6::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float64_divide_scalar_array6(a: f64, b: ExFloat64Array6) -> ExFloat64Array6 {
  ExFloat64Array6::new(a / &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// ADD for 1D arrays and scalars
#[rustler::nif]
pub fn float32_add_array1_array1(a: ExFloat32Array1, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array1_scalar(a: ExFloat32Array1, b: f32) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array1(a: f32, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(a + &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// ADD for 2D arrays and scalars
#[rustler::nif]
pub fn float32_add_array2_array2(a: ExFloat32Array2, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array2_scalar(a: ExFloat32Array2, b: f32) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array2(a: f32, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(a + &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// ADD for 3D arrays and scalars
#[rustler::nif]
pub fn float32_add_array3_array3(a: ExFloat32Array3, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array3_scalar(a: ExFloat32Array3, b: f32) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array3(a: f32, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(a + &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// ADD for 4D arrays and scalars
#[rustler::nif]
pub fn float32_add_array4_array4(a: ExFloat32Array4, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array4_scalar(a: ExFloat32Array4, b: f32) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array4(a: f32, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(a + &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// ADD for 5D arrays and scalars
#[rustler::nif]
pub fn float32_add_array5_array5(a: ExFloat32Array5, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array5_scalar(a: ExFloat32Array5, b: f32) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array5(a: f32, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(a + &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// ADD for 6D arrays and scalars
#[rustler::nif]
pub fn float32_add_array6_array6(a: ExFloat32Array6, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn float32_add_array6_scalar(a: ExFloat32Array6, b: f32) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 + b)
}

#[rustler::nif]
pub fn float32_add_scalar_array6(a: f32, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(a + &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// SUBTRACT for 1D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array1_array1(a: ExFloat32Array1, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array1_scalar(a: ExFloat32Array1, b: f32) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array1(a: f32, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(a - &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// SUBTRACT for 2D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array2_array2(a: ExFloat32Array2, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array2_scalar(a: ExFloat32Array2, b: f32) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array2(a: f32, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(a - &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// SUBTRACT for 3D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array3_array3(a: ExFloat32Array3, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array3_scalar(a: ExFloat32Array3, b: f32) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array3(a: f32, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(a - &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// SUBTRACT for 4D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array4_array4(a: ExFloat32Array4, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array4_scalar(a: ExFloat32Array4, b: f32) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array4(a: f32, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(a - &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// SUBTRACT for 5D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array5_array5(a: ExFloat32Array5, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array5_scalar(a: ExFloat32Array5, b: f32) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array5(a: f32, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(a - &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// SUBTRACT for 6D arrays and scalars
#[rustler::nif]
pub fn float32_subtract_array6_array6(a: ExFloat32Array6, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn float32_subtract_array6_scalar(a: ExFloat32Array6, b: f32) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 - b)
}

#[rustler::nif]
pub fn float32_subtract_scalar_array6(a: f32, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(a - &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// MULTIPLY for 1D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array1_array1(a: ExFloat32Array1, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array1_scalar(a: ExFloat32Array1, b: f32) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array1(a: f32, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(a * &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// MULTIPLY for 2D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array2_array2(a: ExFloat32Array2, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array2_scalar(a: ExFloat32Array2, b: f32) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array2(a: f32, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(a * &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// MULTIPLY for 3D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array3_array3(a: ExFloat32Array3, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array3_scalar(a: ExFloat32Array3, b: f32) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array3(a: f32, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(a * &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// MULTIPLY for 4D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array4_array4(a: ExFloat32Array4, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array4_scalar(a: ExFloat32Array4, b: f32) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array4(a: f32, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(a * &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// MULTIPLY for 5D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array5_array5(a: ExFloat32Array5, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array5_scalar(a: ExFloat32Array5, b: f32) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array5(a: f32, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(a * &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// MULTIPLY for 6D arrays and scalars
#[rustler::nif]
pub fn float32_multiply_array6_array6(a: ExFloat32Array6, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn float32_multiply_array6_scalar(a: ExFloat32Array6, b: f32) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 * b)
}

#[rustler::nif]
pub fn float32_multiply_scalar_array6(a: f32, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(a * &b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// DIVIDE for 1D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array1_array1(a: ExFloat32Array1, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array1_scalar(a: ExFloat32Array1, b: f32) -> ExFloat32Array1 {
  ExFloat32Array1::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array1(a: f32, b: ExFloat32Array1) -> ExFloat32Array1 {
  ExFloat32Array1::new(a / &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// DIVIDE for 2D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array2_array2(a: ExFloat32Array2, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array2_scalar(a: ExFloat32Array2, b: f32) -> ExFloat32Array2 {
  ExFloat32Array2::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array2(a: f32, b: ExFloat32Array2) -> ExFloat32Array2 {
  ExFloat32Array2::new(a / &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// DIVIDE for 3D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array3_array3(a: ExFloat32Array3, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array3_scalar(a: ExFloat32Array3, b: f32) -> ExFloat32Array3 {
  ExFloat32Array3::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array3(a: f32, b: ExFloat32Array3) -> ExFloat32Array3 {
  ExFloat32Array3::new(a / &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// DIVIDE for 4D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array4_array4(a: ExFloat32Array4, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array4_scalar(a: ExFloat32Array4, b: f32) -> ExFloat32Array4 {
  ExFloat32Array4::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array4(a: f32, b: ExFloat32Array4) -> ExFloat32Array4 {
  ExFloat32Array4::new(a / &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// DIVIDE for 5D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array5_array5(a: ExFloat32Array5, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array5_scalar(a: ExFloat32Array5, b: f32) -> ExFloat32Array5 {
  ExFloat32Array5::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array5(a: f32, b: ExFloat32Array5) -> ExFloat32Array5 {
  ExFloat32Array5::new(a / &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// DIVIDE for 6D arrays and scalars
#[rustler::nif]
pub fn float32_divide_array6_array6(a: ExFloat32Array6, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn float32_divide_array6_scalar(a: ExFloat32Array6, b: f32) -> ExFloat32Array6 {
  ExFloat32Array6::new(&a.resource.0 / b)
}

#[rustler::nif]
pub fn float32_divide_scalar_array6(a: f32, b: ExFloat32Array6) -> ExFloat32Array6 {
  ExFloat32Array6::new(a / &b.resource.0)
}


// =========================================
// Complex numbers
// =========================================
#[rustler::nif]
pub fn complex64_add_scalar_scalar(a: ExComplex64, b: ExComplex64) -> ExComplex64 {
  ExComplex64::new(a.resource.0 + b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// ADD for 1D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array1_array1(a: ExComplex64Array1, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array1_scalar(a: ExComplex64Array1, b: ExComplex64) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array1(a: ExComplex64, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// ADD for 2D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array2_array2(a: ExComplex64Array2, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array2_scalar(a: ExComplex64Array2, b: ExComplex64) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array2(a: ExComplex64, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// ADD for 3D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array3_array3(a: ExComplex64Array3, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array3_scalar(a: ExComplex64Array3, b: ExComplex64) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array3(a: ExComplex64, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// ADD for 4D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array4_array4(a: ExComplex64Array4, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array4_scalar(a: ExComplex64Array4, b: ExComplex64) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array4(a: ExComplex64, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// ADD for 5D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array5_array5(a: ExComplex64Array5, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array5_scalar(a: ExComplex64Array5, b: ExComplex64) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array5(a: ExComplex64, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// ADD for 6D arrays and scalars
#[rustler::nif]
pub fn complex64_add_array6_array6(a: ExComplex64Array6, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_array6_scalar(a: ExComplex64Array6, b: ExComplex64) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex64_add_scalar_array6(a: ExComplex64, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(a.resource.0 + &b.resource.0)
}
#[rustler::nif]
pub fn complex64_subtract_scalar_scalar(a: ExComplex64, b: ExComplex64) -> ExComplex64 {
  ExComplex64::new(a.resource.0 - b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// SUBTRACT for 1D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array1_array1(a: ExComplex64Array1, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array1_scalar(a: ExComplex64Array1, b: ExComplex64) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array1(a: ExComplex64, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// SUBTRACT for 2D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array2_array2(a: ExComplex64Array2, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array2_scalar(a: ExComplex64Array2, b: ExComplex64) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array2(a: ExComplex64, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// SUBTRACT for 3D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array3_array3(a: ExComplex64Array3, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array3_scalar(a: ExComplex64Array3, b: ExComplex64) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array3(a: ExComplex64, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// SUBTRACT for 4D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array4_array4(a: ExComplex64Array4, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array4_scalar(a: ExComplex64Array4, b: ExComplex64) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array4(a: ExComplex64, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// SUBTRACT for 5D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array5_array5(a: ExComplex64Array5, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array5_scalar(a: ExComplex64Array5, b: ExComplex64) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array5(a: ExComplex64, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// SUBTRACT for 6D arrays and scalars
#[rustler::nif]
pub fn complex64_subtract_array6_array6(a: ExComplex64Array6, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_array6_scalar(a: ExComplex64Array6, b: ExComplex64) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex64_subtract_scalar_array6(a: ExComplex64, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(a.resource.0 - &b.resource.0)
}
#[rustler::nif]
pub fn complex64_multiply_scalar_scalar(a: ExComplex64, b: ExComplex64) -> ExComplex64 {
  ExComplex64::new(a.resource.0 * b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// MULTIPLY for 1D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array1_array1(a: ExComplex64Array1, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array1_scalar(a: ExComplex64Array1, b: ExComplex64) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array1(a: ExComplex64, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// MULTIPLY for 2D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array2_array2(a: ExComplex64Array2, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array2_scalar(a: ExComplex64Array2, b: ExComplex64) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array2(a: ExComplex64, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// MULTIPLY for 3D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array3_array3(a: ExComplex64Array3, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array3_scalar(a: ExComplex64Array3, b: ExComplex64) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array3(a: ExComplex64, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// MULTIPLY for 4D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array4_array4(a: ExComplex64Array4, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array4_scalar(a: ExComplex64Array4, b: ExComplex64) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array4(a: ExComplex64, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// MULTIPLY for 5D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array5_array5(a: ExComplex64Array5, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array5_scalar(a: ExComplex64Array5, b: ExComplex64) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array5(a: ExComplex64, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// MULTIPLY for 6D arrays and scalars
#[rustler::nif]
pub fn complex64_multiply_array6_array6(a: ExComplex64Array6, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_array6_scalar(a: ExComplex64Array6, b: ExComplex64) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex64_multiply_scalar_array6(a: ExComplex64, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(a.resource.0 * &b.resource.0)
}
#[rustler::nif]
pub fn complex64_divide_scalar_scalar(a: ExComplex64, b: ExComplex64) -> ExComplex64 {
  ExComplex64::new(a.resource.0 / b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// DIVIDE for 1D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array1_array1(a: ExComplex64Array1, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array1_scalar(a: ExComplex64Array1, b: ExComplex64) -> ExComplex64Array1 {
  ExComplex64Array1::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array1(a: ExComplex64, b: ExComplex64Array1) -> ExComplex64Array1 {
  ExComplex64Array1::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// DIVIDE for 2D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array2_array2(a: ExComplex64Array2, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array2_scalar(a: ExComplex64Array2, b: ExComplex64) -> ExComplex64Array2 {
  ExComplex64Array2::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array2(a: ExComplex64, b: ExComplex64Array2) -> ExComplex64Array2 {
  ExComplex64Array2::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// DIVIDE for 3D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array3_array3(a: ExComplex64Array3, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array3_scalar(a: ExComplex64Array3, b: ExComplex64) -> ExComplex64Array3 {
  ExComplex64Array3::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array3(a: ExComplex64, b: ExComplex64Array3) -> ExComplex64Array3 {
  ExComplex64Array3::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// DIVIDE for 4D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array4_array4(a: ExComplex64Array4, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array4_scalar(a: ExComplex64Array4, b: ExComplex64) -> ExComplex64Array4 {
  ExComplex64Array4::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array4(a: ExComplex64, b: ExComplex64Array4) -> ExComplex64Array4 {
  ExComplex64Array4::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// DIVIDE for 5D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array5_array5(a: ExComplex64Array5, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array5_scalar(a: ExComplex64Array5, b: ExComplex64) -> ExComplex64Array5 {
  ExComplex64Array5::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array5(a: ExComplex64, b: ExComplex64Array5) -> ExComplex64Array5 {
  ExComplex64Array5::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// DIVIDE for 6D arrays and scalars
#[rustler::nif]
pub fn complex64_divide_array6_array6(a: ExComplex64Array6, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_array6_scalar(a: ExComplex64Array6, b: ExComplex64) -> ExComplex64Array6 {
  ExComplex64Array6::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex64_divide_scalar_array6(a: ExComplex64, b: ExComplex64Array6) -> ExComplex64Array6 {
  ExComplex64Array6::new(a.resource.0 / &b.resource.0)
}
#[rustler::nif]
pub fn complex32_add_scalar_scalar(a: ExComplex32, b: ExComplex32) -> ExComplex32 {
  ExComplex32::new(a.resource.0 + b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// ADD for 1D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array1_array1(a: ExComplex32Array1, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array1_scalar(a: ExComplex32Array1, b: ExComplex32) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array1(a: ExComplex32, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// ADD for 2D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array2_array2(a: ExComplex32Array2, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array2_scalar(a: ExComplex32Array2, b: ExComplex32) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array2(a: ExComplex32, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// ADD for 3D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array3_array3(a: ExComplex32Array3, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array3_scalar(a: ExComplex32Array3, b: ExComplex32) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array3(a: ExComplex32, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// ADD for 4D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array4_array4(a: ExComplex32Array4, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array4_scalar(a: ExComplex32Array4, b: ExComplex32) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array4(a: ExComplex32, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// ADD for 5D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array5_array5(a: ExComplex32Array5, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array5_scalar(a: ExComplex32Array5, b: ExComplex32) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array5(a: ExComplex32, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(a.resource.0 + &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// ADD for 6D arrays and scalars
#[rustler::nif]
pub fn complex32_add_array6_array6(a: ExComplex32Array6, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 + &b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_array6_scalar(a: ExComplex32Array6, b: ExComplex32) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 + b.resource.0)
}

#[rustler::nif]
pub fn complex32_add_scalar_array6(a: ExComplex32, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(a.resource.0 + &b.resource.0)
}
#[rustler::nif]
pub fn complex32_subtract_scalar_scalar(a: ExComplex32, b: ExComplex32) -> ExComplex32 {
  ExComplex32::new(a.resource.0 - b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// SUBTRACT for 1D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array1_array1(a: ExComplex32Array1, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array1_scalar(a: ExComplex32Array1, b: ExComplex32) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array1(a: ExComplex32, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// SUBTRACT for 2D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array2_array2(a: ExComplex32Array2, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array2_scalar(a: ExComplex32Array2, b: ExComplex32) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array2(a: ExComplex32, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// SUBTRACT for 3D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array3_array3(a: ExComplex32Array3, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array3_scalar(a: ExComplex32Array3, b: ExComplex32) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array3(a: ExComplex32, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// SUBTRACT for 4D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array4_array4(a: ExComplex32Array4, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array4_scalar(a: ExComplex32Array4, b: ExComplex32) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array4(a: ExComplex32, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// SUBTRACT for 5D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array5_array5(a: ExComplex32Array5, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array5_scalar(a: ExComplex32Array5, b: ExComplex32) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array5(a: ExComplex32, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(a.resource.0 - &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// SUBTRACT for 6D arrays and scalars
#[rustler::nif]
pub fn complex32_subtract_array6_array6(a: ExComplex32Array6, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 - &b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_array6_scalar(a: ExComplex32Array6, b: ExComplex32) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 - b.resource.0)
}

#[rustler::nif]
pub fn complex32_subtract_scalar_array6(a: ExComplex32, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(a.resource.0 - &b.resource.0)
}
#[rustler::nif]
pub fn complex32_multiply_scalar_scalar(a: ExComplex32, b: ExComplex32) -> ExComplex32 {
  ExComplex32::new(a.resource.0 * b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// MULTIPLY for 1D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array1_array1(a: ExComplex32Array1, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array1_scalar(a: ExComplex32Array1, b: ExComplex32) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array1(a: ExComplex32, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// MULTIPLY for 2D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array2_array2(a: ExComplex32Array2, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array2_scalar(a: ExComplex32Array2, b: ExComplex32) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array2(a: ExComplex32, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// MULTIPLY for 3D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array3_array3(a: ExComplex32Array3, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array3_scalar(a: ExComplex32Array3, b: ExComplex32) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array3(a: ExComplex32, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// MULTIPLY for 4D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array4_array4(a: ExComplex32Array4, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array4_scalar(a: ExComplex32Array4, b: ExComplex32) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array4(a: ExComplex32, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// MULTIPLY for 5D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array5_array5(a: ExComplex32Array5, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array5_scalar(a: ExComplex32Array5, b: ExComplex32) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array5(a: ExComplex32, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(a.resource.0 * &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// MULTIPLY for 6D arrays and scalars
#[rustler::nif]
pub fn complex32_multiply_array6_array6(a: ExComplex32Array6, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 * &b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_array6_scalar(a: ExComplex32Array6, b: ExComplex32) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 * b.resource.0)
}

#[rustler::nif]
pub fn complex32_multiply_scalar_array6(a: ExComplex32, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(a.resource.0 * &b.resource.0)
}
#[rustler::nif]
pub fn complex32_divide_scalar_scalar(a: ExComplex32, b: ExComplex32) -> ExComplex32 {
  ExComplex32::new(a.resource.0 / b.resource.0)
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
// DIVIDE for 1D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array1_array1(a: ExComplex32Array1, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array1_scalar(a: ExComplex32Array1, b: ExComplex32) -> ExComplex32Array1 {
  ExComplex32Array1::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array1(a: ExComplex32, b: ExComplex32Array1) -> ExComplex32Array1 {
  ExComplex32Array1::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
// DIVIDE for 2D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array2_array2(a: ExComplex32Array2, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array2_scalar(a: ExComplex32Array2, b: ExComplex32) -> ExComplex32Array2 {
  ExComplex32Array2::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array2(a: ExComplex32, b: ExComplex32Array2) -> ExComplex32Array2 {
  ExComplex32Array2::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
// DIVIDE for 3D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array3_array3(a: ExComplex32Array3, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array3_scalar(a: ExComplex32Array3, b: ExComplex32) -> ExComplex32Array3 {
  ExComplex32Array3::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array3(a: ExComplex32, b: ExComplex32Array3) -> ExComplex32Array3 {
  ExComplex32Array3::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
// DIVIDE for 4D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array4_array4(a: ExComplex32Array4, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array4_scalar(a: ExComplex32Array4, b: ExComplex32) -> ExComplex32Array4 {
  ExComplex32Array4::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array4(a: ExComplex32, b: ExComplex32Array4) -> ExComplex32Array4 {
  ExComplex32Array4::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
// DIVIDE for 5D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array5_array5(a: ExComplex32Array5, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array5_scalar(a: ExComplex32Array5, b: ExComplex32) -> ExComplex32Array5 {
  ExComplex32Array5::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array5(a: ExComplex32, b: ExComplex32Array5) -> ExComplex32Array5 {
  ExComplex32Array5::new(a.resource.0 / &b.resource.0)
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
// DIVIDE for 6D arrays and scalars
#[rustler::nif]
pub fn complex32_divide_array6_array6(a: ExComplex32Array6, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 / &b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_array6_scalar(a: ExComplex32Array6, b: ExComplex32) -> ExComplex32Array6 {
  ExComplex32Array6::new(&a.resource.0 / b.resource.0)
}

#[rustler::nif]
pub fn complex32_divide_scalar_array6(a: ExComplex32, b: ExComplex32Array6) -> ExComplex32Array6 {
  ExComplex32Array6::new(a.resource.0 / &b.resource.0)
}
