// ========================================================================================
// THIS FILE HAS BEEN AUTOGENERATED - Do not edit directly
// ----------------------------------------------------------------------------------------
// Edit the template at 'scripts/rust_generator/templates/array_unary_operations.rs' instead
// ========================================================================================

use crate::datatypes::*;

// =========================================
// Special operations, implemented manually
// =========================================

#[rustler::nif]
pub fn float64_transpose(a: ExFloat64Array2) -> ExFloat64Array2 {
  let m = a.resource.0.clone().reversed_axes();
  ExFloat64Array2::new(m)
}

#[rustler::nif]
pub fn float32_transpose(a: ExFloat32Array2) -> ExFloat32Array2 {
  let m = a.resource.0.clone().reversed_axes();
  ExFloat32Array2::new(m)
}

#[rustler::nif]
pub fn complex64_transpose(a: ExComplex64Array2) -> ExComplex64Array2 {
  let m = a.resource.0.clone().reversed_axes();
  ExComplex64Array2::new(m)
}

#[rustler::nif]
pub fn complex32_transpose(a: ExComplex32Array2) -> ExComplex32Array2 {
  let m = a.resource.0.clone().reversed_axes();
  ExComplex32Array2::new(m)
}


// =========================================
// Real numbers
// =========================================

// -----------------------------------------
// 1D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array1_sum(a: ExFloat64Array1) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array2_sum(a: ExFloat64Array2) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array3_sum(a: ExFloat64Array3) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array4_sum(a: ExFloat64Array4) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array5_sum(a: ExFloat64Array5) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float64_array6_sum(a: ExFloat64Array6) -> f64 {
  a.resource.0.sum()
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array1_sum(a: ExFloat32Array1) -> f32 {
  a.resource.0.sum()
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array2_sum(a: ExFloat32Array2) -> f32 {
  a.resource.0.sum()
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array3_sum(a: ExFloat32Array3) -> f32 {
  a.resource.0.sum()
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array4_sum(a: ExFloat32Array4) -> f32 {
  a.resource.0.sum()
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array5_sum(a: ExFloat32Array5) -> f32 {
  a.resource.0.sum()
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float32_array6_sum(a: ExFloat32Array6) -> f32 {
  a.resource.0.sum()
}


// =========================================
// Complex numbers
// =========================================

// -----------------------------------------
// 1D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array1_sum(a: ExComplex64Array1) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array2_sum(a: ExComplex64Array2) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array3_sum(a: ExComplex64Array3) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array4_sum(a: ExComplex64Array4) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array5_sum(a: ExComplex64Array5) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex64_array6_sum(a: ExComplex64Array6) -> ExComplex64 {
  ExComplex64::new(a.resource.0.sum())
}

// -----------------------------------------
// 1D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array1_sum(a: ExComplex32Array1) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}

// -----------------------------------------
// 2D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array2_sum(a: ExComplex32Array2) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}

// -----------------------------------------
// 3D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array3_sum(a: ExComplex32Array3) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}

// -----------------------------------------
// 4D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array4_sum(a: ExComplex32Array4) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}

// -----------------------------------------
// 5D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array5_sum(a: ExComplex32Array5) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}

// -----------------------------------------
// 6D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex32_array6_sum(a: ExComplex32Array6) -> ExComplex32 {
  ExComplex32::new(a.resource.0.sum())
}
