defmodule SciEx.SciExNif do
  @moduledoc false

  use Rustler,
    otp_app: :sci_ex,
    crate: :sci_ex_nif

  # Stats
  def stats_array1_beta_pdf(_s, _shape_a, _shape_b), do: err()
  def stats_array1_beta_cdf(_s, _shape_a, _shape_b), do: err()
  def stats_array1_beta_inverse_cdf(_s, _shape_a, _shape_b), do: err()

  def stats_array1_cauchy_pdf(_s, _location, _scale), do: err()
  def stats_array1_cauchy_cdf(_s, _location, _scale), do: err()
  def stats_array1_cauchy_inverse_cdf(_s, _location, _scale), do: err()

  def stats_array1_chi_pdf(_s, _freedom), do: err()
  def stats_array1_chi_cdf(_s, _freedom), do: err()
  def stats_array1_chi_inverse_cdf(_s, _freedom), do: err()

  def stats_array1_chi_squared_pdf(_s, _freedom), do: err()
  def stats_array1_chi_squared_cdf(_s, _freedom), do: err()
  def stats_array1_chi_squared_inverse_cdf(_s, _freedom), do: err()

  # The Dirac distribution doesn't have a PDF
  def stats_array1_dirac_cdf(_s, _v), do: err()
  def stats_array1_dirac_inverse_cdf(_s, _v), do: err()

  def stats_array1_erlang_pdf(_s, _shape, _rate), do: err()
  def stats_array1_erlang_cdf(_s, _shape, _rate), do: err()
  def stats_array1_erlang_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_exp_pdf(_s, _rate), do: err()
  def stats_array1_exp_cdf(_s, _rate), do: err()
  def stats_array1_exp_inverse_cdf(_s, _rate), do: err()

  def stats_array1_fisher_snedecor_pdf(_s, _freedom_1, _freedom_2), do: err()
  def stats_array1_fisher_snedecor_cdf(_s, _freedom_1, _freedom_2), do: err()
  def stats_array1_fisher_snedecor_inverse_cdf(_s, _freedom_1, _freedom_2), do: err()

  def stats_array1_gamma_pdf(_s, _shape, _rate), do: err()
  def stats_array1_gamma_cdf(_s, _shape, _rate), do: err()
  def stats_array1_gamma_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_gumbel_pdf(_s, _location, _scale), do: err()
  def stats_array1_gumbel_cdf(_s, _location, _scale), do: err()
  def stats_array1_gumbel_inverse_cdf(_s, _location, _scale), do: err()

  def stats_array1_inverse_gamma_pdf(_s, _shape, _rate), do: err()
  def stats_array1_inverse_gamma_cdf(_s, _shape, _rate), do: err()
  def stats_array1_inverse_gamma_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_laplace_pdf(_s, _location, _scale), do: err()
  def stats_array1_laplace_cdf(_s, _location, _scale), do: err()
  def stats_array1_laplace_inverse_cdf(_s, _location, _scale), do: err()

  # Sample random variables
  def stats_draw_from_beta(_seed, _a, _b, _nr_of_draws), do: err()
  def stats_draw_from_cauchy(_seed, _median, _scale, _nr_of_draws), do: err()
  def stats_draw_from_chi(_seed, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_chi_squared(_seed, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_dirac(_seed, _v, _nr_of_draws), do: err()
  def stats_draw_from_erlang(_seed, _shape, _rate, _nr_of_draws), do: err()
  def stats_draw_from_exp(_seed, _rate, _nr_of_draws), do: err()
  def stats_draw_from_fisher_snedecor(_seed, _freedom_1, _freedom_2, _nr_of_draws), do: err()
  def stats_draw_from_gamma(_seed, _mean, _variance, _nr_of_draws), do: err()
  def stats_draw_from_gumbel(_seed, _location, _scale, _nr_of_draws), do: err()
  def stats_draw_from_inverse_gamma(_seed, _shape, _rate, _nr_of_draws), do: err()
  def stats_draw_from_laplace(_seed, _location, _scale, _nr_of_draws), do: err()
  def stats_draw_from_log_normal(_seed, _mean, _variance, _nr_of_draws), do: err()
  def stats_draw_from_negative_binomial(_seed, _r, _p, _nr_of_draws), do: err()
  def stats_draw_from_normal(_seed, _mu, _sigma, _nr_of_draws), do: err()
  def stats_draw_from_pareto(_seed, _scale, _shape, _nr_of_draws), do: err()
  def stats_draw_from_students_t(_seed, _location, _scale, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_triangular(_seed, _min, _max, _mode, _nr_of_draws), do: err()
  def stats_draw_from_uniform(_seed, _min, _max, _nr_of_draws), do: err()
  def stats_draw_from_weibull(_seed, _shape, _scale, _nr_of_draws), do: err()

  def float64_array1_inspect(_array1), do: err()
  def float64_array2_inspect(_array2), do: err()
  def float64_array3_inspect(_array3), do: err()
  def float64_array4_inspect(_array4), do: err()
  def float64_array5_inspect(_array5), do: err()
  def float64_array6_inspect(_array5), do: err()

  # Don't edit the lines below, they are automatically generated
  # %% BEGIN:GENERATED:f64-array-comparisons %%
  def float64_array1_equal(_a, _b), do: err()
  def float64_array1_not_equal(_a, _b), do: err()
  def float64_array1_all_not_equal(_a, _b), do: err()
  def float64_array1_all_greater_than(_a, _b), do: err()
  def float64_array1_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array1_all_less_than(_a, _b), do: err()
  def float64_array1_all_less_than_or_equal(_a, _b), do: err()
  def float64_array2_equal(_a, _b), do: err()
  def float64_array2_not_equal(_a, _b), do: err()
  def float64_array2_all_not_equal(_a, _b), do: err()
  def float64_array2_all_greater_than(_a, _b), do: err()
  def float64_array2_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array2_all_less_than(_a, _b), do: err()
  def float64_array2_all_less_than_or_equal(_a, _b), do: err()
  def float64_array3_equal(_a, _b), do: err()
  def float64_array3_not_equal(_a, _b), do: err()
  def float64_array3_all_not_equal(_a, _b), do: err()
  def float64_array3_all_greater_than(_a, _b), do: err()
  def float64_array3_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array3_all_less_than(_a, _b), do: err()
  def float64_array3_all_less_than_or_equal(_a, _b), do: err()
  def float64_array4_equal(_a, _b), do: err()
  def float64_array4_not_equal(_a, _b), do: err()
  def float64_array4_all_not_equal(_a, _b), do: err()
  def float64_array4_all_greater_than(_a, _b), do: err()
  def float64_array4_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array4_all_less_than(_a, _b), do: err()
  def float64_array4_all_less_than_or_equal(_a, _b), do: err()
  def float64_array5_equal(_a, _b), do: err()
  def float64_array5_not_equal(_a, _b), do: err()
  def float64_array5_all_not_equal(_a, _b), do: err()
  def float64_array5_all_greater_than(_a, _b), do: err()
  def float64_array5_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array5_all_less_than(_a, _b), do: err()
  def float64_array5_all_less_than_or_equal(_a, _b), do: err()
  def float64_array6_equal(_a, _b), do: err()
  def float64_array6_not_equal(_a, _b), do: err()
  def float64_array6_all_not_equal(_a, _b), do: err()
  def float64_array6_all_greater_than(_a, _b), do: err()
  def float64_array6_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array6_all_less_than(_a, _b), do: err()
  def float64_array6_all_less_than_or_equal(_a, _b), do: err()
  # %% END:GENERATED:f64-array-comparisons %%

  # Don't edit the lines below, they are automatically generated
  # %% BEGIN:GENERATED:f64-functions %%
  def float64_array1_acos(_array1), do: err()
  def float64_array1_acosh(_array1), do: err()
  def float64_array1_asin(_array1), do: err()
  def float64_array1_asinh(_array1), do: err()
  def float64_array1_atan(_array1), do: err()
  def float64_array1_atan2(_array1, _other), do: err()
  def float64_array1_atanh(_array1), do: err()
  def float64_array1_cbrt(_array1), do: err()
  def float64_array1_ceil(_array1), do: err()
  def float64_array1_cos(_array1), do: err()
  def float64_array1_cosh(_array1), do: err()
  def float64_array1_div_euclid(_array1, _rhs), do: err()
  def float64_array1_erf(_array1), do: err()
  def float64_array1_erfc(_array1), do: err()
  def float64_array1_exp(_array1), do: err()
  def float64_array1_exp2(_array1), do: err()
  def float64_array1_exp_m1(_array1), do: err()
  def float64_array1_floor(_array1), do: err()
  def float64_array1_fract(_array1), do: err()
  def float64_array1_hypot(_array1, _other), do: err()
  def float64_array1_j0(_array1), do: err()
  def float64_array1_j1(_array1), do: err()
  def float64_array1_lgamma(_array1), do: err()
  def float64_array1_ln(_array1), do: err()
  def float64_array1_ln_1p(_array1), do: err()
  def float64_array1_log(_array1, _base), do: err()
  def float64_array1_log10(_array1), do: err()
  def float64_array1_log2(_array1), do: err()
  def float64_array1_mul_add(_array1, _a, _b), do: err()
  def float64_array1_powf(_array1, _n), do: err()
  def float64_array1_powi(_array1, _n), do: err()
  def float64_array1_rem_euclid(_array1, _rhs), do: err()
  def float64_array1_round(_array1), do: err()
  def float64_array1_round_ties_even(_array1), do: err()
  def float64_array1_sin(_array1), do: err()
  def float64_array1_sinh(_array1), do: err()
  def float64_array1_sqrt(_array1), do: err()
  def float64_array1_tan(_array1), do: err()
  def float64_array1_tanh(_array1), do: err()
  def float64_array1_trunc(_array1), do: err()
  def float64_array1_y0(_array1), do: err()
  def float64_array1_y1(_array1), do: err()
  def float64_array2_acos(_array2), do: err()
  def float64_array2_acosh(_array2), do: err()
  def float64_array2_asin(_array2), do: err()
  def float64_array2_asinh(_array2), do: err()
  def float64_array2_atan(_array2), do: err()
  def float64_array2_atan2(_array2, _other), do: err()
  def float64_array2_atanh(_array2), do: err()
  def float64_array2_cbrt(_array2), do: err()
  def float64_array2_ceil(_array2), do: err()
  def float64_array2_cos(_array2), do: err()
  def float64_array2_cosh(_array2), do: err()
  def float64_array2_div_euclid(_array2, _rhs), do: err()
  def float64_array2_erf(_array2), do: err()
  def float64_array2_erfc(_array2), do: err()
  def float64_array2_exp(_array2), do: err()
  def float64_array2_exp2(_array2), do: err()
  def float64_array2_exp_m1(_array2), do: err()
  def float64_array2_floor(_array2), do: err()
  def float64_array2_fract(_array2), do: err()
  def float64_array2_hypot(_array2, _other), do: err()
  def float64_array2_j0(_array2), do: err()
  def float64_array2_j1(_array2), do: err()
  def float64_array2_lgamma(_array2), do: err()
  def float64_array2_ln(_array2), do: err()
  def float64_array2_ln_1p(_array2), do: err()
  def float64_array2_log(_array2, _base), do: err()
  def float64_array2_log10(_array2), do: err()
  def float64_array2_log2(_array2), do: err()
  def float64_array2_mul_add(_array2, _a, _b), do: err()
  def float64_array2_powf(_array2, _n), do: err()
  def float64_array2_powi(_array2, _n), do: err()
  def float64_array2_rem_euclid(_array2, _rhs), do: err()
  def float64_array2_round(_array2), do: err()
  def float64_array2_round_ties_even(_array2), do: err()
  def float64_array2_sin(_array2), do: err()
  def float64_array2_sinh(_array2), do: err()
  def float64_array2_sqrt(_array2), do: err()
  def float64_array2_tan(_array2), do: err()
  def float64_array2_tanh(_array2), do: err()
  def float64_array2_trunc(_array2), do: err()
  def float64_array2_y0(_array2), do: err()
  def float64_array2_y1(_array2), do: err()
  def float64_array3_acos(_array3), do: err()
  def float64_array3_acosh(_array3), do: err()
  def float64_array3_asin(_array3), do: err()
  def float64_array3_asinh(_array3), do: err()
  def float64_array3_atan(_array3), do: err()
  def float64_array3_atan2(_array3, _other), do: err()
  def float64_array3_atanh(_array3), do: err()
  def float64_array3_cbrt(_array3), do: err()
  def float64_array3_ceil(_array3), do: err()
  def float64_array3_cos(_array3), do: err()
  def float64_array3_cosh(_array3), do: err()
  def float64_array3_div_euclid(_array3, _rhs), do: err()
  def float64_array3_erf(_array3), do: err()
  def float64_array3_erfc(_array3), do: err()
  def float64_array3_exp(_array3), do: err()
  def float64_array3_exp2(_array3), do: err()
  def float64_array3_exp_m1(_array3), do: err()
  def float64_array3_floor(_array3), do: err()
  def float64_array3_fract(_array3), do: err()
  def float64_array3_hypot(_array3, _other), do: err()
  def float64_array3_j0(_array3), do: err()
  def float64_array3_j1(_array3), do: err()
  def float64_array3_lgamma(_array3), do: err()
  def float64_array3_ln(_array3), do: err()
  def float64_array3_ln_1p(_array3), do: err()
  def float64_array3_log(_array3, _base), do: err()
  def float64_array3_log10(_array3), do: err()
  def float64_array3_log2(_array3), do: err()
  def float64_array3_mul_add(_array3, _a, _b), do: err()
  def float64_array3_powf(_array3, _n), do: err()
  def float64_array3_powi(_array3, _n), do: err()
  def float64_array3_rem_euclid(_array3, _rhs), do: err()
  def float64_array3_round(_array3), do: err()
  def float64_array3_round_ties_even(_array3), do: err()
  def float64_array3_sin(_array3), do: err()
  def float64_array3_sinh(_array3), do: err()
  def float64_array3_sqrt(_array3), do: err()
  def float64_array3_tan(_array3), do: err()
  def float64_array3_tanh(_array3), do: err()
  def float64_array3_trunc(_array3), do: err()
  def float64_array3_y0(_array3), do: err()
  def float64_array3_y1(_array3), do: err()
  def float64_array4_acos(_array4), do: err()
  def float64_array4_acosh(_array4), do: err()
  def float64_array4_asin(_array4), do: err()
  def float64_array4_asinh(_array4), do: err()
  def float64_array4_atan(_array4), do: err()
  def float64_array4_atan2(_array4, _other), do: err()
  def float64_array4_atanh(_array4), do: err()
  def float64_array4_cbrt(_array4), do: err()
  def float64_array4_ceil(_array4), do: err()
  def float64_array4_cos(_array4), do: err()
  def float64_array4_cosh(_array4), do: err()
  def float64_array4_div_euclid(_array4, _rhs), do: err()
  def float64_array4_erf(_array4), do: err()
  def float64_array4_erfc(_array4), do: err()
  def float64_array4_exp(_array4), do: err()
  def float64_array4_exp2(_array4), do: err()
  def float64_array4_exp_m1(_array4), do: err()
  def float64_array4_floor(_array4), do: err()
  def float64_array4_fract(_array4), do: err()
  def float64_array4_hypot(_array4, _other), do: err()
  def float64_array4_j0(_array4), do: err()
  def float64_array4_j1(_array4), do: err()
  def float64_array4_lgamma(_array4), do: err()
  def float64_array4_ln(_array4), do: err()
  def float64_array4_ln_1p(_array4), do: err()
  def float64_array4_log(_array4, _base), do: err()
  def float64_array4_log10(_array4), do: err()
  def float64_array4_log2(_array4), do: err()
  def float64_array4_mul_add(_array4, _a, _b), do: err()
  def float64_array4_powf(_array4, _n), do: err()
  def float64_array4_powi(_array4, _n), do: err()
  def float64_array4_rem_euclid(_array4, _rhs), do: err()
  def float64_array4_round(_array4), do: err()
  def float64_array4_round_ties_even(_array4), do: err()
  def float64_array4_sin(_array4), do: err()
  def float64_array4_sinh(_array4), do: err()
  def float64_array4_sqrt(_array4), do: err()
  def float64_array4_tan(_array4), do: err()
  def float64_array4_tanh(_array4), do: err()
  def float64_array4_trunc(_array4), do: err()
  def float64_array4_y0(_array4), do: err()
  def float64_array4_y1(_array4), do: err()
  def float64_array5_acos(_array5), do: err()
  def float64_array5_acosh(_array5), do: err()
  def float64_array5_asin(_array5), do: err()
  def float64_array5_asinh(_array5), do: err()
  def float64_array5_atan(_array5), do: err()
  def float64_array5_atan2(_array5, _other), do: err()
  def float64_array5_atanh(_array5), do: err()
  def float64_array5_cbrt(_array5), do: err()
  def float64_array5_ceil(_array5), do: err()
  def float64_array5_cos(_array5), do: err()
  def float64_array5_cosh(_array5), do: err()
  def float64_array5_div_euclid(_array5, _rhs), do: err()
  def float64_array5_erf(_array5), do: err()
  def float64_array5_erfc(_array5), do: err()
  def float64_array5_exp(_array5), do: err()
  def float64_array5_exp2(_array5), do: err()
  def float64_array5_exp_m1(_array5), do: err()
  def float64_array5_floor(_array5), do: err()
  def float64_array5_fract(_array5), do: err()
  def float64_array5_hypot(_array5, _other), do: err()
  def float64_array5_j0(_array5), do: err()
  def float64_array5_j1(_array5), do: err()
  def float64_array5_lgamma(_array5), do: err()
  def float64_array5_ln(_array5), do: err()
  def float64_array5_ln_1p(_array5), do: err()
  def float64_array5_log(_array5, _base), do: err()
  def float64_array5_log10(_array5), do: err()
  def float64_array5_log2(_array5), do: err()
  def float64_array5_mul_add(_array5, _a, _b), do: err()
  def float64_array5_powf(_array5, _n), do: err()
  def float64_array5_powi(_array5, _n), do: err()
  def float64_array5_rem_euclid(_array5, _rhs), do: err()
  def float64_array5_round(_array5), do: err()
  def float64_array5_round_ties_even(_array5), do: err()
  def float64_array5_sin(_array5), do: err()
  def float64_array5_sinh(_array5), do: err()
  def float64_array5_sqrt(_array5), do: err()
  def float64_array5_tan(_array5), do: err()
  def float64_array5_tanh(_array5), do: err()
  def float64_array5_trunc(_array5), do: err()
  def float64_array5_y0(_array5), do: err()
  def float64_array5_y1(_array5), do: err()
  def float64_array6_acos(_array6), do: err()
  def float64_array6_acosh(_array6), do: err()
  def float64_array6_asin(_array6), do: err()
  def float64_array6_asinh(_array6), do: err()
  def float64_array6_atan(_array6), do: err()
  def float64_array6_atan2(_array6, _other), do: err()
  def float64_array6_atanh(_array6), do: err()
  def float64_array6_cbrt(_array6), do: err()
  def float64_array6_ceil(_array6), do: err()
  def float64_array6_cos(_array6), do: err()
  def float64_array6_cosh(_array6), do: err()
  def float64_array6_div_euclid(_array6, _rhs), do: err()
  def float64_array6_erf(_array6), do: err()
  def float64_array6_erfc(_array6), do: err()
  def float64_array6_exp(_array6), do: err()
  def float64_array6_exp2(_array6), do: err()
  def float64_array6_exp_m1(_array6), do: err()
  def float64_array6_floor(_array6), do: err()
  def float64_array6_fract(_array6), do: err()
  def float64_array6_hypot(_array6, _other), do: err()
  def float64_array6_j0(_array6), do: err()
  def float64_array6_j1(_array6), do: err()
  def float64_array6_lgamma(_array6), do: err()
  def float64_array6_ln(_array6), do: err()
  def float64_array6_ln_1p(_array6), do: err()
  def float64_array6_log(_array6, _base), do: err()
  def float64_array6_log10(_array6), do: err()
  def float64_array6_log2(_array6), do: err()
  def float64_array6_mul_add(_array6, _a, _b), do: err()
  def float64_array6_powf(_array6, _n), do: err()
  def float64_array6_powi(_array6, _n), do: err()
  def float64_array6_rem_euclid(_array6, _rhs), do: err()
  def float64_array6_round(_array6), do: err()
  def float64_array6_round_ties_even(_array6), do: err()
  def float64_array6_sin(_array6), do: err()
  def float64_array6_sinh(_array6), do: err()
  def float64_array6_sqrt(_array6), do: err()
  def float64_array6_tan(_array6), do: err()
  def float64_array6_tanh(_array6), do: err()
  def float64_array6_trunc(_array6), do: err()
  def float64_array6_y0(_array6), do: err()
  def float64_array6_y1(_array6), do: err()
  # %% END:GENERATED:f64-functions %%

  # %% BEGIN:GENERATED:f64-array-builders %%
  def float64_array1_zeros(_n1), do: err()
  def float64_array2_zeros(_n1, _n2), do: err()
  def float64_array3_zeros(_n1, _n2, _n3), do: err()
  def float64_array4_zeros(_n1, _n2, _n3, _n4), do: err()
  def float64_array5_zeros(_n1, _n2, _n3, _n4, _n5), do: err()
  def float64_array6_zeros(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  def float64_array1_ones(_n1), do: err()
  def float64_array2_ones(_n1, _n2), do: err()
  def float64_array3_ones(_n1, _n2, _n3), do: err()
  def float64_array4_ones(_n1, _n2, _n3, _n4), do: err()
  def float64_array5_ones(_n1, _n2, _n3, _n4, _n5), do: err()
  def float64_array6_ones(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  # %% END:GENERATED:f64-array-builders %%

  def float64_add_array1_array1(_a, _b), do: err()
  def float64_add_array1_f64(_a, _b), do: err()
  def float64_add_f64_array1(_a, _b), do: err()

  defp err(), do: :erlang.nif_error(:nif_not_loaded)
end
