defmodule SciEx.SciExNif do
  @moduledoc false

  use Rustler,
    otp_app: :sci_ex,
    crate: :sci_ex_nif

  # Stats
  def stats_array1_beta_pdf(_s, _shape_a, _shape_b), do: err()
  def stats_array1_beta_cdf(_s, _shape_a, _shape_b), do: err()
  def stats_array1_beta_inverse_cdf(_s, _shape_a, _shape_b), do: err()

  def stats_array1_cauchy_pdf(_s, _location, _scale), do: err()
  def stats_array1_cauchy_cdf(_s, _location, _scale), do: err()
  def stats_array1_cauchy_inverse_cdf(_s, _location, _scale), do: err()

  def stats_array1_chi_pdf(_s, _freedom), do: err()
  def stats_array1_chi_cdf(_s, _freedom), do: err()
  def stats_array1_chi_inverse_cdf(_s, _freedom), do: err()

  def stats_array1_chi_squared_pdf(_s, _freedom), do: err()
  def stats_array1_chi_squared_cdf(_s, _freedom), do: err()
  def stats_array1_chi_squared_inverse_cdf(_s, _freedom), do: err()

  # The Dirac distribution doesn't have a PDF
  def stats_array1_dirac_cdf(_s, _v), do: err()
  def stats_array1_dirac_inverse_cdf(_s, _v), do: err()

  def stats_array1_erlang_pdf(_s, _shape, _rate), do: err()
  def stats_array1_erlang_cdf(_s, _shape, _rate), do: err()
  def stats_array1_erlang_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_exp_pdf(_s, _rate), do: err()
  def stats_array1_exp_cdf(_s, _rate), do: err()
  def stats_array1_exp_inverse_cdf(_s, _rate), do: err()

  def stats_array1_fisher_snedecor_pdf(_s, _freedom_1, _freedom_2), do: err()
  def stats_array1_fisher_snedecor_cdf(_s, _freedom_1, _freedom_2), do: err()
  def stats_array1_fisher_snedecor_inverse_cdf(_s, _freedom_1, _freedom_2), do: err()

  def stats_array1_gamma_pdf(_s, _shape, _rate), do: err()
  def stats_array1_gamma_cdf(_s, _shape, _rate), do: err()
  def stats_array1_gamma_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_gumbel_pdf(_s, _location, _scale), do: err()
  def stats_array1_gumbel_cdf(_s, _location, _scale), do: err()
  def stats_array1_gumbel_inverse_cdf(_s, _location, _scale), do: err()

  def stats_array1_inverse_gamma_pdf(_s, _shape, _rate), do: err()
  def stats_array1_inverse_gamma_cdf(_s, _shape, _rate), do: err()
  def stats_array1_inverse_gamma_inverse_cdf(_s, _shape, _rate), do: err()

  def stats_array1_laplace_pdf(_s, _location, _scale), do: err()
  def stats_array1_laplace_cdf(_s, _location, _scale), do: err()
  def stats_array1_laplace_inverse_cdf(_s, _location, _scale), do: err()

  # Sample random variables
  def stats_draw_from_beta(_seed, _a, _b, _nr_of_draws), do: err()
  def stats_draw_from_cauchy(_seed, _median, _scale, _nr_of_draws), do: err()
  def stats_draw_from_chi(_seed, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_chi_squared(_seed, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_dirac(_seed, _v, _nr_of_draws), do: err()
  def stats_draw_from_erlang(_seed, _shape, _rate, _nr_of_draws), do: err()
  def stats_draw_from_exp(_seed, _rate, _nr_of_draws), do: err()
  def stats_draw_from_fisher_snedecor(_seed, _freedom_1, _freedom_2, _nr_of_draws), do: err()
  def stats_draw_from_gamma(_seed, _mean, _variance, _nr_of_draws), do: err()
  def stats_draw_from_gumbel(_seed, _location, _scale, _nr_of_draws), do: err()
  def stats_draw_from_inverse_gamma(_seed, _shape, _rate, _nr_of_draws), do: err()
  def stats_draw_from_laplace(_seed, _location, _scale, _nr_of_draws), do: err()
  def stats_draw_from_log_normal(_seed, _mean, _variance, _nr_of_draws), do: err()
  def stats_draw_from_negative_binomial(_seed, _r, _p, _nr_of_draws), do: err()
  def stats_draw_from_normal(_seed, _mu, _sigma, _nr_of_draws), do: err()
  def stats_draw_from_pareto(_seed, _scale, _shape, _nr_of_draws), do: err()
  def stats_draw_from_students_t(_seed, _location, _scale, _freedom, _nr_of_draws), do: err()
  def stats_draw_from_triangular(_seed, _min, _max, _mode, _nr_of_draws), do: err()
  def stats_draw_from_uniform(_seed, _min, _max, _nr_of_draws), do: err()
  def stats_draw_from_weibull(_seed, _shape, _scale, _nr_of_draws), do: err()

  def float64_array1_inspect(_array1), do: err()
  def float64_array2_inspect(_array2), do: err()
  def float64_array3_inspect(_array3), do: err()
  def float64_array4_inspect(_array4), do: err()
  def float64_array5_inspect(_array5), do: err()
  def float64_array6_inspect(_array5), do: err()

  def float32_array1_inspect(_array1), do: err()
  def float32_array2_inspect(_array2), do: err()
  def float32_array3_inspect(_array3), do: err()
  def float32_array4_inspect(_array4), do: err()
  def float32_array5_inspect(_array5), do: err()
  def float32_array6_inspect(_array5), do: err()

  # Don't edit the lines below, they are automatically generated
  # %% BEGIN:GENERATED:float-array-comparisons %%
  def float64_array1_equal(_a, _b), do: err()
  def float64_array1_not_equal(_a, _b), do: err()
  def float64_array1_all_not_equal(_a, _b), do: err()
  def float64_array1_all_greater_than(_a, _b), do: err()
  def float64_array1_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array1_all_less_than(_a, _b), do: err()
  def float64_array1_all_less_than_or_equal(_a, _b), do: err()
  def float64_array2_equal(_a, _b), do: err()
  def float64_array2_not_equal(_a, _b), do: err()
  def float64_array2_all_not_equal(_a, _b), do: err()
  def float64_array2_all_greater_than(_a, _b), do: err()
  def float64_array2_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array2_all_less_than(_a, _b), do: err()
  def float64_array2_all_less_than_or_equal(_a, _b), do: err()
  def float64_array3_equal(_a, _b), do: err()
  def float64_array3_not_equal(_a, _b), do: err()
  def float64_array3_all_not_equal(_a, _b), do: err()
  def float64_array3_all_greater_than(_a, _b), do: err()
  def float64_array3_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array3_all_less_than(_a, _b), do: err()
  def float64_array3_all_less_than_or_equal(_a, _b), do: err()
  def float64_array4_equal(_a, _b), do: err()
  def float64_array4_not_equal(_a, _b), do: err()
  def float64_array4_all_not_equal(_a, _b), do: err()
  def float64_array4_all_greater_than(_a, _b), do: err()
  def float64_array4_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array4_all_less_than(_a, _b), do: err()
  def float64_array4_all_less_than_or_equal(_a, _b), do: err()
  def float64_array5_equal(_a, _b), do: err()
  def float64_array5_not_equal(_a, _b), do: err()
  def float64_array5_all_not_equal(_a, _b), do: err()
  def float64_array5_all_greater_than(_a, _b), do: err()
  def float64_array5_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array5_all_less_than(_a, _b), do: err()
  def float64_array5_all_less_than_or_equal(_a, _b), do: err()
  def float64_array6_equal(_a, _b), do: err()
  def float64_array6_not_equal(_a, _b), do: err()
  def float64_array6_all_not_equal(_a, _b), do: err()
  def float64_array6_all_greater_than(_a, _b), do: err()
  def float64_array6_all_greater_than_or_equal(_a, _b), do: err()
  def float64_array6_all_less_than(_a, _b), do: err()
  def float64_array6_all_less_than_or_equal(_a, _b), do: err()
  def float32_array1_equal(_a, _b), do: err()
  def float32_array1_not_equal(_a, _b), do: err()
  def float32_array1_all_not_equal(_a, _b), do: err()
  def float32_array1_all_greater_than(_a, _b), do: err()
  def float32_array1_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array1_all_less_than(_a, _b), do: err()
  def float32_array1_all_less_than_or_equal(_a, _b), do: err()
  def float32_array2_equal(_a, _b), do: err()
  def float32_array2_not_equal(_a, _b), do: err()
  def float32_array2_all_not_equal(_a, _b), do: err()
  def float32_array2_all_greater_than(_a, _b), do: err()
  def float32_array2_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array2_all_less_than(_a, _b), do: err()
  def float32_array2_all_less_than_or_equal(_a, _b), do: err()
  def float32_array3_equal(_a, _b), do: err()
  def float32_array3_not_equal(_a, _b), do: err()
  def float32_array3_all_not_equal(_a, _b), do: err()
  def float32_array3_all_greater_than(_a, _b), do: err()
  def float32_array3_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array3_all_less_than(_a, _b), do: err()
  def float32_array3_all_less_than_or_equal(_a, _b), do: err()
  def float32_array4_equal(_a, _b), do: err()
  def float32_array4_not_equal(_a, _b), do: err()
  def float32_array4_all_not_equal(_a, _b), do: err()
  def float32_array4_all_greater_than(_a, _b), do: err()
  def float32_array4_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array4_all_less_than(_a, _b), do: err()
  def float32_array4_all_less_than_or_equal(_a, _b), do: err()
  def float32_array5_equal(_a, _b), do: err()
  def float32_array5_not_equal(_a, _b), do: err()
  def float32_array5_all_not_equal(_a, _b), do: err()
  def float32_array5_all_greater_than(_a, _b), do: err()
  def float32_array5_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array5_all_less_than(_a, _b), do: err()
  def float32_array5_all_less_than_or_equal(_a, _b), do: err()
  def float32_array6_equal(_a, _b), do: err()
  def float32_array6_not_equal(_a, _b), do: err()
  def float32_array6_all_not_equal(_a, _b), do: err()
  def float32_array6_all_greater_than(_a, _b), do: err()
  def float32_array6_all_greater_than_or_equal(_a, _b), do: err()
  def float32_array6_all_less_than(_a, _b), do: err()
  def float32_array6_all_less_than_or_equal(_a, _b), do: err()
  # %% END:GENERATED:float-array-comparisons %%

  # Don't edit the lines below, they are automatically generated
  # %% BEGIN:GENERATED:float-functions %%
  def float64_acos_array1(_array1), do: err()
  def float64_acosh_array1(_array1), do: err()
  def float64_asin_array1(_array1), do: err()
  def float64_asinh_array1(_array1), do: err()
  def float64_atan2_array1(_array1, _other), do: err()
  def float64_atan_array1(_array1), do: err()
  def float64_atanh_array1(_array1), do: err()
  def float64_cbrt_array1(_array1), do: err()
  def float64_ceil_array1(_array1), do: err()
  def float64_cos_array1(_array1), do: err()
  def float64_cosh_array1(_array1), do: err()
  def float64_div_euclid_array1(_array1, _rhs), do: err()
  def float64_erf_array1(_array1), do: err()
  def float64_erfc_array1(_array1), do: err()
  def float64_exp2_array1(_array1), do: err()
  def float64_exp_array1(_array1), do: err()
  def float64_exp_m1_array1(_array1), do: err()
  def float64_floor_array1(_array1), do: err()
  def float64_fract_array1(_array1), do: err()
  def float64_hypot_array1(_array1, _other), do: err()
  def float64_j0_array1(_array1), do: err()
  def float64_j1_array1(_array1), do: err()
  def float64_lgamma_array1(_array1), do: err()
  def float64_ln_1p_array1(_array1), do: err()
  def float64_ln_array1(_array1), do: err()
  def float64_log10_array1(_array1), do: err()
  def float64_log2_array1(_array1), do: err()
  def float64_log_array1(_array1, _base), do: err()
  def float64_mul_add_array1(_array1, _a, _b), do: err()
  def float64_powf_array1(_array1, _n), do: err()
  def float64_powi_array1(_array1, _n), do: err()
  def float64_rem_euclid_array1(_array1, _rhs), do: err()
  def float64_round_array1(_array1), do: err()
  def float64_round_ties_even_array1(_array1), do: err()
  def float64_sin_array1(_array1), do: err()
  def float64_sinh_array1(_array1), do: err()
  def float64_sqrt_array1(_array1), do: err()
  def float64_tan_array1(_array1), do: err()
  def float64_tanh_array1(_array1), do: err()
  def float64_trunc_array1(_array1), do: err()
  def float64_y0_array1(_array1), do: err()
  def float64_y1_array1(_array1), do: err()
  def float64_acos_array2(_array2), do: err()
  def float64_acosh_array2(_array2), do: err()
  def float64_asin_array2(_array2), do: err()
  def float64_asinh_array2(_array2), do: err()
  def float64_atan2_array2(_array2, _other), do: err()
  def float64_atan_array2(_array2), do: err()
  def float64_atanh_array2(_array2), do: err()
  def float64_cbrt_array2(_array2), do: err()
  def float64_ceil_array2(_array2), do: err()
  def float64_cos_array2(_array2), do: err()
  def float64_cosh_array2(_array2), do: err()
  def float64_div_euclid_array2(_array2, _rhs), do: err()
  def float64_erf_array2(_array2), do: err()
  def float64_erfc_array2(_array2), do: err()
  def float64_exp2_array2(_array2), do: err()
  def float64_exp_array2(_array2), do: err()
  def float64_exp_m1_array2(_array2), do: err()
  def float64_floor_array2(_array2), do: err()
  def float64_fract_array2(_array2), do: err()
  def float64_hypot_array2(_array2, _other), do: err()
  def float64_j0_array2(_array2), do: err()
  def float64_j1_array2(_array2), do: err()
  def float64_lgamma_array2(_array2), do: err()
  def float64_ln_1p_array2(_array2), do: err()
  def float64_ln_array2(_array2), do: err()
  def float64_log10_array2(_array2), do: err()
  def float64_log2_array2(_array2), do: err()
  def float64_log_array2(_array2, _base), do: err()
  def float64_mul_add_array2(_array2, _a, _b), do: err()
  def float64_powf_array2(_array2, _n), do: err()
  def float64_powi_array2(_array2, _n), do: err()
  def float64_rem_euclid_array2(_array2, _rhs), do: err()
  def float64_round_array2(_array2), do: err()
  def float64_round_ties_even_array2(_array2), do: err()
  def float64_sin_array2(_array2), do: err()
  def float64_sinh_array2(_array2), do: err()
  def float64_sqrt_array2(_array2), do: err()
  def float64_tan_array2(_array2), do: err()
  def float64_tanh_array2(_array2), do: err()
  def float64_trunc_array2(_array2), do: err()
  def float64_y0_array2(_array2), do: err()
  def float64_y1_array2(_array2), do: err()
  def float64_acos_array3(_array3), do: err()
  def float64_acosh_array3(_array3), do: err()
  def float64_asin_array3(_array3), do: err()
  def float64_asinh_array3(_array3), do: err()
  def float64_atan2_array3(_array3, _other), do: err()
  def float64_atan_array3(_array3), do: err()
  def float64_atanh_array3(_array3), do: err()
  def float64_cbrt_array3(_array3), do: err()
  def float64_ceil_array3(_array3), do: err()
  def float64_cos_array3(_array3), do: err()
  def float64_cosh_array3(_array3), do: err()
  def float64_div_euclid_array3(_array3, _rhs), do: err()
  def float64_erf_array3(_array3), do: err()
  def float64_erfc_array3(_array3), do: err()
  def float64_exp2_array3(_array3), do: err()
  def float64_exp_array3(_array3), do: err()
  def float64_exp_m1_array3(_array3), do: err()
  def float64_floor_array3(_array3), do: err()
  def float64_fract_array3(_array3), do: err()
  def float64_hypot_array3(_array3, _other), do: err()
  def float64_j0_array3(_array3), do: err()
  def float64_j1_array3(_array3), do: err()
  def float64_lgamma_array3(_array3), do: err()
  def float64_ln_1p_array3(_array3), do: err()
  def float64_ln_array3(_array3), do: err()
  def float64_log10_array3(_array3), do: err()
  def float64_log2_array3(_array3), do: err()
  def float64_log_array3(_array3, _base), do: err()
  def float64_mul_add_array3(_array3, _a, _b), do: err()
  def float64_powf_array3(_array3, _n), do: err()
  def float64_powi_array3(_array3, _n), do: err()
  def float64_rem_euclid_array3(_array3, _rhs), do: err()
  def float64_round_array3(_array3), do: err()
  def float64_round_ties_even_array3(_array3), do: err()
  def float64_sin_array3(_array3), do: err()
  def float64_sinh_array3(_array3), do: err()
  def float64_sqrt_array3(_array3), do: err()
  def float64_tan_array3(_array3), do: err()
  def float64_tanh_array3(_array3), do: err()
  def float64_trunc_array3(_array3), do: err()
  def float64_y0_array3(_array3), do: err()
  def float64_y1_array3(_array3), do: err()
  def float64_acos_array4(_array4), do: err()
  def float64_acosh_array4(_array4), do: err()
  def float64_asin_array4(_array4), do: err()
  def float64_asinh_array4(_array4), do: err()
  def float64_atan2_array4(_array4, _other), do: err()
  def float64_atan_array4(_array4), do: err()
  def float64_atanh_array4(_array4), do: err()
  def float64_cbrt_array4(_array4), do: err()
  def float64_ceil_array4(_array4), do: err()
  def float64_cos_array4(_array4), do: err()
  def float64_cosh_array4(_array4), do: err()
  def float64_div_euclid_array4(_array4, _rhs), do: err()
  def float64_erf_array4(_array4), do: err()
  def float64_erfc_array4(_array4), do: err()
  def float64_exp2_array4(_array4), do: err()
  def float64_exp_array4(_array4), do: err()
  def float64_exp_m1_array4(_array4), do: err()
  def float64_floor_array4(_array4), do: err()
  def float64_fract_array4(_array4), do: err()
  def float64_hypot_array4(_array4, _other), do: err()
  def float64_j0_array4(_array4), do: err()
  def float64_j1_array4(_array4), do: err()
  def float64_lgamma_array4(_array4), do: err()
  def float64_ln_1p_array4(_array4), do: err()
  def float64_ln_array4(_array4), do: err()
  def float64_log10_array4(_array4), do: err()
  def float64_log2_array4(_array4), do: err()
  def float64_log_array4(_array4, _base), do: err()
  def float64_mul_add_array4(_array4, _a, _b), do: err()
  def float64_powf_array4(_array4, _n), do: err()
  def float64_powi_array4(_array4, _n), do: err()
  def float64_rem_euclid_array4(_array4, _rhs), do: err()
  def float64_round_array4(_array4), do: err()
  def float64_round_ties_even_array4(_array4), do: err()
  def float64_sin_array4(_array4), do: err()
  def float64_sinh_array4(_array4), do: err()
  def float64_sqrt_array4(_array4), do: err()
  def float64_tan_array4(_array4), do: err()
  def float64_tanh_array4(_array4), do: err()
  def float64_trunc_array4(_array4), do: err()
  def float64_y0_array4(_array4), do: err()
  def float64_y1_array4(_array4), do: err()
  def float64_acos_array5(_array5), do: err()
  def float64_acosh_array5(_array5), do: err()
  def float64_asin_array5(_array5), do: err()
  def float64_asinh_array5(_array5), do: err()
  def float64_atan2_array5(_array5, _other), do: err()
  def float64_atan_array5(_array5), do: err()
  def float64_atanh_array5(_array5), do: err()
  def float64_cbrt_array5(_array5), do: err()
  def float64_ceil_array5(_array5), do: err()
  def float64_cos_array5(_array5), do: err()
  def float64_cosh_array5(_array5), do: err()
  def float64_div_euclid_array5(_array5, _rhs), do: err()
  def float64_erf_array5(_array5), do: err()
  def float64_erfc_array5(_array5), do: err()
  def float64_exp2_array5(_array5), do: err()
  def float64_exp_array5(_array5), do: err()
  def float64_exp_m1_array5(_array5), do: err()
  def float64_floor_array5(_array5), do: err()
  def float64_fract_array5(_array5), do: err()
  def float64_hypot_array5(_array5, _other), do: err()
  def float64_j0_array5(_array5), do: err()
  def float64_j1_array5(_array5), do: err()
  def float64_lgamma_array5(_array5), do: err()
  def float64_ln_1p_array5(_array5), do: err()
  def float64_ln_array5(_array5), do: err()
  def float64_log10_array5(_array5), do: err()
  def float64_log2_array5(_array5), do: err()
  def float64_log_array5(_array5, _base), do: err()
  def float64_mul_add_array5(_array5, _a, _b), do: err()
  def float64_powf_array5(_array5, _n), do: err()
  def float64_powi_array5(_array5, _n), do: err()
  def float64_rem_euclid_array5(_array5, _rhs), do: err()
  def float64_round_array5(_array5), do: err()
  def float64_round_ties_even_array5(_array5), do: err()
  def float64_sin_array5(_array5), do: err()
  def float64_sinh_array5(_array5), do: err()
  def float64_sqrt_array5(_array5), do: err()
  def float64_tan_array5(_array5), do: err()
  def float64_tanh_array5(_array5), do: err()
  def float64_trunc_array5(_array5), do: err()
  def float64_y0_array5(_array5), do: err()
  def float64_y1_array5(_array5), do: err()
  def float64_acos_array6(_array6), do: err()
  def float64_acosh_array6(_array6), do: err()
  def float64_asin_array6(_array6), do: err()
  def float64_asinh_array6(_array6), do: err()
  def float64_atan2_array6(_array6, _other), do: err()
  def float64_atan_array6(_array6), do: err()
  def float64_atanh_array6(_array6), do: err()
  def float64_cbrt_array6(_array6), do: err()
  def float64_ceil_array6(_array6), do: err()
  def float64_cos_array6(_array6), do: err()
  def float64_cosh_array6(_array6), do: err()
  def float64_div_euclid_array6(_array6, _rhs), do: err()
  def float64_erf_array6(_array6), do: err()
  def float64_erfc_array6(_array6), do: err()
  def float64_exp2_array6(_array6), do: err()
  def float64_exp_array6(_array6), do: err()
  def float64_exp_m1_array6(_array6), do: err()
  def float64_floor_array6(_array6), do: err()
  def float64_fract_array6(_array6), do: err()
  def float64_hypot_array6(_array6, _other), do: err()
  def float64_j0_array6(_array6), do: err()
  def float64_j1_array6(_array6), do: err()
  def float64_lgamma_array6(_array6), do: err()
  def float64_ln_1p_array6(_array6), do: err()
  def float64_ln_array6(_array6), do: err()
  def float64_log10_array6(_array6), do: err()
  def float64_log2_array6(_array6), do: err()
  def float64_log_array6(_array6, _base), do: err()
  def float64_mul_add_array6(_array6, _a, _b), do: err()
  def float64_powf_array6(_array6, _n), do: err()
  def float64_powi_array6(_array6, _n), do: err()
  def float64_rem_euclid_array6(_array6, _rhs), do: err()
  def float64_round_array6(_array6), do: err()
  def float64_round_ties_even_array6(_array6), do: err()
  def float64_sin_array6(_array6), do: err()
  def float64_sinh_array6(_array6), do: err()
  def float64_sqrt_array6(_array6), do: err()
  def float64_tan_array6(_array6), do: err()
  def float64_tanh_array6(_array6), do: err()
  def float64_trunc_array6(_array6), do: err()
  def float64_y0_array6(_array6), do: err()
  def float64_y1_array6(_array6), do: err()
  def float32_acos_array1(_array1), do: err()
  def float32_acosh_array1(_array1), do: err()
  def float32_asin_array1(_array1), do: err()
  def float32_asinh_array1(_array1), do: err()
  def float32_atan2_array1(_array1, _other), do: err()
  def float32_atan_array1(_array1), do: err()
  def float32_atanh_array1(_array1), do: err()
  def float32_cbrt_array1(_array1), do: err()
  def float32_ceil_array1(_array1), do: err()
  def float32_cos_array1(_array1), do: err()
  def float32_cosh_array1(_array1), do: err()
  def float32_div_euclid_array1(_array1, _rhs), do: err()
  def float32_erf_array1(_array1), do: err()
  def float32_erfc_array1(_array1), do: err()
  def float32_exp2_array1(_array1), do: err()
  def float32_exp_array1(_array1), do: err()
  def float32_exp_m1_array1(_array1), do: err()
  def float32_floor_array1(_array1), do: err()
  def float32_fract_array1(_array1), do: err()
  def float32_hypot_array1(_array1, _other), do: err()
  def float32_j0_array1(_array1), do: err()
  def float32_j1_array1(_array1), do: err()
  def float32_lgamma_array1(_array1), do: err()
  def float32_ln_1p_array1(_array1), do: err()
  def float32_ln_array1(_array1), do: err()
  def float32_log10_array1(_array1), do: err()
  def float32_log2_array1(_array1), do: err()
  def float32_log_array1(_array1, _base), do: err()
  def float32_mul_add_array1(_array1, _a, _b), do: err()
  def float32_powf_array1(_array1, _n), do: err()
  def float32_powi_array1(_array1, _n), do: err()
  def float32_rem_euclid_array1(_array1, _rhs), do: err()
  def float32_round_array1(_array1), do: err()
  def float32_round_ties_even_array1(_array1), do: err()
  def float32_sin_array1(_array1), do: err()
  def float32_sinh_array1(_array1), do: err()
  def float32_sqrt_array1(_array1), do: err()
  def float32_tan_array1(_array1), do: err()
  def float32_tanh_array1(_array1), do: err()
  def float32_trunc_array1(_array1), do: err()
  def float32_y0_array1(_array1), do: err()
  def float32_y1_array1(_array1), do: err()
  def float32_acos_array2(_array2), do: err()
  def float32_acosh_array2(_array2), do: err()
  def float32_asin_array2(_array2), do: err()
  def float32_asinh_array2(_array2), do: err()
  def float32_atan2_array2(_array2, _other), do: err()
  def float32_atan_array2(_array2), do: err()
  def float32_atanh_array2(_array2), do: err()
  def float32_cbrt_array2(_array2), do: err()
  def float32_ceil_array2(_array2), do: err()
  def float32_cos_array2(_array2), do: err()
  def float32_cosh_array2(_array2), do: err()
  def float32_div_euclid_array2(_array2, _rhs), do: err()
  def float32_erf_array2(_array2), do: err()
  def float32_erfc_array2(_array2), do: err()
  def float32_exp2_array2(_array2), do: err()
  def float32_exp_array2(_array2), do: err()
  def float32_exp_m1_array2(_array2), do: err()
  def float32_floor_array2(_array2), do: err()
  def float32_fract_array2(_array2), do: err()
  def float32_hypot_array2(_array2, _other), do: err()
  def float32_j0_array2(_array2), do: err()
  def float32_j1_array2(_array2), do: err()
  def float32_lgamma_array2(_array2), do: err()
  def float32_ln_1p_array2(_array2), do: err()
  def float32_ln_array2(_array2), do: err()
  def float32_log10_array2(_array2), do: err()
  def float32_log2_array2(_array2), do: err()
  def float32_log_array2(_array2, _base), do: err()
  def float32_mul_add_array2(_array2, _a, _b), do: err()
  def float32_powf_array2(_array2, _n), do: err()
  def float32_powi_array2(_array2, _n), do: err()
  def float32_rem_euclid_array2(_array2, _rhs), do: err()
  def float32_round_array2(_array2), do: err()
  def float32_round_ties_even_array2(_array2), do: err()
  def float32_sin_array2(_array2), do: err()
  def float32_sinh_array2(_array2), do: err()
  def float32_sqrt_array2(_array2), do: err()
  def float32_tan_array2(_array2), do: err()
  def float32_tanh_array2(_array2), do: err()
  def float32_trunc_array2(_array2), do: err()
  def float32_y0_array2(_array2), do: err()
  def float32_y1_array2(_array2), do: err()
  def float32_acos_array3(_array3), do: err()
  def float32_acosh_array3(_array3), do: err()
  def float32_asin_array3(_array3), do: err()
  def float32_asinh_array3(_array3), do: err()
  def float32_atan2_array3(_array3, _other), do: err()
  def float32_atan_array3(_array3), do: err()
  def float32_atanh_array3(_array3), do: err()
  def float32_cbrt_array3(_array3), do: err()
  def float32_ceil_array3(_array3), do: err()
  def float32_cos_array3(_array3), do: err()
  def float32_cosh_array3(_array3), do: err()
  def float32_div_euclid_array3(_array3, _rhs), do: err()
  def float32_erf_array3(_array3), do: err()
  def float32_erfc_array3(_array3), do: err()
  def float32_exp2_array3(_array3), do: err()
  def float32_exp_array3(_array3), do: err()
  def float32_exp_m1_array3(_array3), do: err()
  def float32_floor_array3(_array3), do: err()
  def float32_fract_array3(_array3), do: err()
  def float32_hypot_array3(_array3, _other), do: err()
  def float32_j0_array3(_array3), do: err()
  def float32_j1_array3(_array3), do: err()
  def float32_lgamma_array3(_array3), do: err()
  def float32_ln_1p_array3(_array3), do: err()
  def float32_ln_array3(_array3), do: err()
  def float32_log10_array3(_array3), do: err()
  def float32_log2_array3(_array3), do: err()
  def float32_log_array3(_array3, _base), do: err()
  def float32_mul_add_array3(_array3, _a, _b), do: err()
  def float32_powf_array3(_array3, _n), do: err()
  def float32_powi_array3(_array3, _n), do: err()
  def float32_rem_euclid_array3(_array3, _rhs), do: err()
  def float32_round_array3(_array3), do: err()
  def float32_round_ties_even_array3(_array3), do: err()
  def float32_sin_array3(_array3), do: err()
  def float32_sinh_array3(_array3), do: err()
  def float32_sqrt_array3(_array3), do: err()
  def float32_tan_array3(_array3), do: err()
  def float32_tanh_array3(_array3), do: err()
  def float32_trunc_array3(_array3), do: err()
  def float32_y0_array3(_array3), do: err()
  def float32_y1_array3(_array3), do: err()
  def float32_acos_array4(_array4), do: err()
  def float32_acosh_array4(_array4), do: err()
  def float32_asin_array4(_array4), do: err()
  def float32_asinh_array4(_array4), do: err()
  def float32_atan2_array4(_array4, _other), do: err()
  def float32_atan_array4(_array4), do: err()
  def float32_atanh_array4(_array4), do: err()
  def float32_cbrt_array4(_array4), do: err()
  def float32_ceil_array4(_array4), do: err()
  def float32_cos_array4(_array4), do: err()
  def float32_cosh_array4(_array4), do: err()
  def float32_div_euclid_array4(_array4, _rhs), do: err()
  def float32_erf_array4(_array4), do: err()
  def float32_erfc_array4(_array4), do: err()
  def float32_exp2_array4(_array4), do: err()
  def float32_exp_array4(_array4), do: err()
  def float32_exp_m1_array4(_array4), do: err()
  def float32_floor_array4(_array4), do: err()
  def float32_fract_array4(_array4), do: err()
  def float32_hypot_array4(_array4, _other), do: err()
  def float32_j0_array4(_array4), do: err()
  def float32_j1_array4(_array4), do: err()
  def float32_lgamma_array4(_array4), do: err()
  def float32_ln_1p_array4(_array4), do: err()
  def float32_ln_array4(_array4), do: err()
  def float32_log10_array4(_array4), do: err()
  def float32_log2_array4(_array4), do: err()
  def float32_log_array4(_array4, _base), do: err()
  def float32_mul_add_array4(_array4, _a, _b), do: err()
  def float32_powf_array4(_array4, _n), do: err()
  def float32_powi_array4(_array4, _n), do: err()
  def float32_rem_euclid_array4(_array4, _rhs), do: err()
  def float32_round_array4(_array4), do: err()
  def float32_round_ties_even_array4(_array4), do: err()
  def float32_sin_array4(_array4), do: err()
  def float32_sinh_array4(_array4), do: err()
  def float32_sqrt_array4(_array4), do: err()
  def float32_tan_array4(_array4), do: err()
  def float32_tanh_array4(_array4), do: err()
  def float32_trunc_array4(_array4), do: err()
  def float32_y0_array4(_array4), do: err()
  def float32_y1_array4(_array4), do: err()
  def float32_acos_array5(_array5), do: err()
  def float32_acosh_array5(_array5), do: err()
  def float32_asin_array5(_array5), do: err()
  def float32_asinh_array5(_array5), do: err()
  def float32_atan2_array5(_array5, _other), do: err()
  def float32_atan_array5(_array5), do: err()
  def float32_atanh_array5(_array5), do: err()
  def float32_cbrt_array5(_array5), do: err()
  def float32_ceil_array5(_array5), do: err()
  def float32_cos_array5(_array5), do: err()
  def float32_cosh_array5(_array5), do: err()
  def float32_div_euclid_array5(_array5, _rhs), do: err()
  def float32_erf_array5(_array5), do: err()
  def float32_erfc_array5(_array5), do: err()
  def float32_exp2_array5(_array5), do: err()
  def float32_exp_array5(_array5), do: err()
  def float32_exp_m1_array5(_array5), do: err()
  def float32_floor_array5(_array5), do: err()
  def float32_fract_array5(_array5), do: err()
  def float32_hypot_array5(_array5, _other), do: err()
  def float32_j0_array5(_array5), do: err()
  def float32_j1_array5(_array5), do: err()
  def float32_lgamma_array5(_array5), do: err()
  def float32_ln_1p_array5(_array5), do: err()
  def float32_ln_array5(_array5), do: err()
  def float32_log10_array5(_array5), do: err()
  def float32_log2_array5(_array5), do: err()
  def float32_log_array5(_array5, _base), do: err()
  def float32_mul_add_array5(_array5, _a, _b), do: err()
  def float32_powf_array5(_array5, _n), do: err()
  def float32_powi_array5(_array5, _n), do: err()
  def float32_rem_euclid_array5(_array5, _rhs), do: err()
  def float32_round_array5(_array5), do: err()
  def float32_round_ties_even_array5(_array5), do: err()
  def float32_sin_array5(_array5), do: err()
  def float32_sinh_array5(_array5), do: err()
  def float32_sqrt_array5(_array5), do: err()
  def float32_tan_array5(_array5), do: err()
  def float32_tanh_array5(_array5), do: err()
  def float32_trunc_array5(_array5), do: err()
  def float32_y0_array5(_array5), do: err()
  def float32_y1_array5(_array5), do: err()
  def float32_acos_array6(_array6), do: err()
  def float32_acosh_array6(_array6), do: err()
  def float32_asin_array6(_array6), do: err()
  def float32_asinh_array6(_array6), do: err()
  def float32_atan2_array6(_array6, _other), do: err()
  def float32_atan_array6(_array6), do: err()
  def float32_atanh_array6(_array6), do: err()
  def float32_cbrt_array6(_array6), do: err()
  def float32_ceil_array6(_array6), do: err()
  def float32_cos_array6(_array6), do: err()
  def float32_cosh_array6(_array6), do: err()
  def float32_div_euclid_array6(_array6, _rhs), do: err()
  def float32_erf_array6(_array6), do: err()
  def float32_erfc_array6(_array6), do: err()
  def float32_exp2_array6(_array6), do: err()
  def float32_exp_array6(_array6), do: err()
  def float32_exp_m1_array6(_array6), do: err()
  def float32_floor_array6(_array6), do: err()
  def float32_fract_array6(_array6), do: err()
  def float32_hypot_array6(_array6, _other), do: err()
  def float32_j0_array6(_array6), do: err()
  def float32_j1_array6(_array6), do: err()
  def float32_lgamma_array6(_array6), do: err()
  def float32_ln_1p_array6(_array6), do: err()
  def float32_ln_array6(_array6), do: err()
  def float32_log10_array6(_array6), do: err()
  def float32_log2_array6(_array6), do: err()
  def float32_log_array6(_array6, _base), do: err()
  def float32_mul_add_array6(_array6, _a, _b), do: err()
  def float32_powf_array6(_array6, _n), do: err()
  def float32_powi_array6(_array6, _n), do: err()
  def float32_rem_euclid_array6(_array6, _rhs), do: err()
  def float32_round_array6(_array6), do: err()
  def float32_round_ties_even_array6(_array6), do: err()
  def float32_sin_array6(_array6), do: err()
  def float32_sinh_array6(_array6), do: err()
  def float32_sqrt_array6(_array6), do: err()
  def float32_tan_array6(_array6), do: err()
  def float32_tanh_array6(_array6), do: err()
  def float32_trunc_array6(_array6), do: err()
  def float32_y0_array6(_array6), do: err()
  def float32_y1_array6(_array6), do: err()
  # %% END:GENERATED:float-functions %%

  # %% BEGIN:GENERATED:float-array-builders %%
  def float64_array1_zeros(_n1), do: err()
  def float64_array2_zeros(_n1, _n2), do: err()
  def float64_array3_zeros(_n1, _n2, _n3), do: err()
  def float64_array4_zeros(_n1, _n2, _n3, _n4), do: err()
  def float64_array5_zeros(_n1, _n2, _n3, _n4, _n5), do: err()
  def float64_array6_zeros(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  def float64_array1_ones(_n1), do: err()
  def float64_array2_ones(_n1, _n2), do: err()
  def float64_array3_ones(_n1, _n2, _n3), do: err()
  def float64_array4_ones(_n1, _n2, _n3, _n4), do: err()
  def float64_array5_ones(_n1, _n2, _n3, _n4, _n5), do: err()
  def float64_array6_ones(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  def float32_array1_zeros(_n1), do: err()
  def float32_array2_zeros(_n1, _n2), do: err()
  def float32_array3_zeros(_n1, _n2, _n3), do: err()
  def float32_array4_zeros(_n1, _n2, _n3, _n4), do: err()
  def float32_array5_zeros(_n1, _n2, _n3, _n4, _n5), do: err()
  def float32_array6_zeros(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  def float32_array1_ones(_n1), do: err()
  def float32_array2_ones(_n1, _n2), do: err()
  def float32_array3_ones(_n1, _n2, _n3), do: err()
  def float32_array4_ones(_n1, _n2, _n3, _n4), do: err()
  def float32_array5_ones(_n1, _n2, _n3, _n4, _n5), do: err()
  def float32_array6_ones(_n1, _n2, _n3, _n4, _n5, _n6), do: err()
  # %% END:GENERATED:float-array-builders %%

  # %% BEGIN:GENERATED:float-array-binary-operations %%
  def float64_add_array1_array1(_a, _b), do: err()
  def float64_add_array1_scalar(_a, _b), do: err()
  def float64_add_scalar_array1(_a, _b), do: err()
  def float64_subtract_array1_array1(_a, _b), do: err()
  def float64_subtract_array1_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array1(_a, _b), do: err()
  def float64_multiply_array1_array1(_a, _b), do: err()
  def float64_multiply_array1_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array1(_a, _b), do: err()
  def float64_divide_array1_array1(_a, _b), do: err()
  def float64_divide_array1_scalar(_a, _b), do: err()
  def float64_divide_scalar_array1(_a, _b), do: err()
  def float64_add_array2_array2(_a, _b), do: err()
  def float64_add_array2_scalar(_a, _b), do: err()
  def float64_add_scalar_array2(_a, _b), do: err()
  def float64_subtract_array2_array2(_a, _b), do: err()
  def float64_subtract_array2_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array2(_a, _b), do: err()
  def float64_multiply_array2_array2(_a, _b), do: err()
  def float64_multiply_array2_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array2(_a, _b), do: err()
  def float64_divide_array2_array2(_a, _b), do: err()
  def float64_divide_array2_scalar(_a, _b), do: err()
  def float64_divide_scalar_array2(_a, _b), do: err()
  def float64_add_array3_array3(_a, _b), do: err()
  def float64_add_array3_scalar(_a, _b), do: err()
  def float64_add_scalar_array3(_a, _b), do: err()
  def float64_subtract_array3_array3(_a, _b), do: err()
  def float64_subtract_array3_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array3(_a, _b), do: err()
  def float64_multiply_array3_array3(_a, _b), do: err()
  def float64_multiply_array3_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array3(_a, _b), do: err()
  def float64_divide_array3_array3(_a, _b), do: err()
  def float64_divide_array3_scalar(_a, _b), do: err()
  def float64_divide_scalar_array3(_a, _b), do: err()
  def float64_add_array4_array4(_a, _b), do: err()
  def float64_add_array4_scalar(_a, _b), do: err()
  def float64_add_scalar_array4(_a, _b), do: err()
  def float64_subtract_array4_array4(_a, _b), do: err()
  def float64_subtract_array4_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array4(_a, _b), do: err()
  def float64_multiply_array4_array4(_a, _b), do: err()
  def float64_multiply_array4_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array4(_a, _b), do: err()
  def float64_divide_array4_array4(_a, _b), do: err()
  def float64_divide_array4_scalar(_a, _b), do: err()
  def float64_divide_scalar_array4(_a, _b), do: err()
  def float64_add_array5_array5(_a, _b), do: err()
  def float64_add_array5_scalar(_a, _b), do: err()
  def float64_add_scalar_array5(_a, _b), do: err()
  def float64_subtract_array5_array5(_a, _b), do: err()
  def float64_subtract_array5_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array5(_a, _b), do: err()
  def float64_multiply_array5_array5(_a, _b), do: err()
  def float64_multiply_array5_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array5(_a, _b), do: err()
  def float64_divide_array5_array5(_a, _b), do: err()
  def float64_divide_array5_scalar(_a, _b), do: err()
  def float64_divide_scalar_array5(_a, _b), do: err()
  def float64_add_array6_array6(_a, _b), do: err()
  def float64_add_array6_scalar(_a, _b), do: err()
  def float64_add_scalar_array6(_a, _b), do: err()
  def float64_subtract_array6_array6(_a, _b), do: err()
  def float64_subtract_array6_scalar(_a, _b), do: err()
  def float64_subtract_scalar_array6(_a, _b), do: err()
  def float64_multiply_array6_array6(_a, _b), do: err()
  def float64_multiply_array6_scalar(_a, _b), do: err()
  def float64_multiply_scalar_array6(_a, _b), do: err()
  def float64_divide_array6_array6(_a, _b), do: err()
  def float64_divide_array6_scalar(_a, _b), do: err()
  def float64_divide_scalar_array6(_a, _b), do: err()
  def float32_add_array1_array1(_a, _b), do: err()
  def float32_add_array1_scalar(_a, _b), do: err()
  def float32_add_scalar_array1(_a, _b), do: err()
  def float32_subtract_array1_array1(_a, _b), do: err()
  def float32_subtract_array1_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array1(_a, _b), do: err()
  def float32_multiply_array1_array1(_a, _b), do: err()
  def float32_multiply_array1_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array1(_a, _b), do: err()
  def float32_divide_array1_array1(_a, _b), do: err()
  def float32_divide_array1_scalar(_a, _b), do: err()
  def float32_divide_scalar_array1(_a, _b), do: err()
  def float32_add_array2_array2(_a, _b), do: err()
  def float32_add_array2_scalar(_a, _b), do: err()
  def float32_add_scalar_array2(_a, _b), do: err()
  def float32_subtract_array2_array2(_a, _b), do: err()
  def float32_subtract_array2_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array2(_a, _b), do: err()
  def float32_multiply_array2_array2(_a, _b), do: err()
  def float32_multiply_array2_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array2(_a, _b), do: err()
  def float32_divide_array2_array2(_a, _b), do: err()
  def float32_divide_array2_scalar(_a, _b), do: err()
  def float32_divide_scalar_array2(_a, _b), do: err()
  def float32_add_array3_array3(_a, _b), do: err()
  def float32_add_array3_scalar(_a, _b), do: err()
  def float32_add_scalar_array3(_a, _b), do: err()
  def float32_subtract_array3_array3(_a, _b), do: err()
  def float32_subtract_array3_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array3(_a, _b), do: err()
  def float32_multiply_array3_array3(_a, _b), do: err()
  def float32_multiply_array3_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array3(_a, _b), do: err()
  def float32_divide_array3_array3(_a, _b), do: err()
  def float32_divide_array3_scalar(_a, _b), do: err()
  def float32_divide_scalar_array3(_a, _b), do: err()
  def float32_add_array4_array4(_a, _b), do: err()
  def float32_add_array4_scalar(_a, _b), do: err()
  def float32_add_scalar_array4(_a, _b), do: err()
  def float32_subtract_array4_array4(_a, _b), do: err()
  def float32_subtract_array4_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array4(_a, _b), do: err()
  def float32_multiply_array4_array4(_a, _b), do: err()
  def float32_multiply_array4_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array4(_a, _b), do: err()
  def float32_divide_array4_array4(_a, _b), do: err()
  def float32_divide_array4_scalar(_a, _b), do: err()
  def float32_divide_scalar_array4(_a, _b), do: err()
  def float32_add_array5_array5(_a, _b), do: err()
  def float32_add_array5_scalar(_a, _b), do: err()
  def float32_add_scalar_array5(_a, _b), do: err()
  def float32_subtract_array5_array5(_a, _b), do: err()
  def float32_subtract_array5_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array5(_a, _b), do: err()
  def float32_multiply_array5_array5(_a, _b), do: err()
  def float32_multiply_array5_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array5(_a, _b), do: err()
  def float32_divide_array5_array5(_a, _b), do: err()
  def float32_divide_array5_scalar(_a, _b), do: err()
  def float32_divide_scalar_array5(_a, _b), do: err()
  def float32_add_array6_array6(_a, _b), do: err()
  def float32_add_array6_scalar(_a, _b), do: err()
  def float32_add_scalar_array6(_a, _b), do: err()
  def float32_subtract_array6_array6(_a, _b), do: err()
  def float32_subtract_array6_scalar(_a, _b), do: err()
  def float32_subtract_scalar_array6(_a, _b), do: err()
  def float32_multiply_array6_array6(_a, _b), do: err()
  def float32_multiply_array6_scalar(_a, _b), do: err()
  def float32_multiply_scalar_array6(_a, _b), do: err()
  def float32_divide_array6_array6(_a, _b), do: err()
  def float32_divide_array6_scalar(_a, _b), do: err()
  def float32_divide_scalar_array6(_a, _b), do: err()
  # %% END:GENERATED:float-array-binary-operations %%

  defp err(), do: :erlang.nif_error(:nif_not_loaded)
end
