// ========================================================================================
// THIS FILE HAS BEEN AUTOGENERATED - Do not edit directly
// ----------------------------------------------------------------------------------------
// Edit the template at 'scripts/rust_generator/templates/array_unary_operations.rs' instead
// ========================================================================================

use crate::datatypes::*;

// =========================================
// Special operations, implemented manually
// =========================================
<%= for {typ_low, typ_upper} <- [{"float", "Float"}, {"complex", "Complex"}], bits <- [64, 32] do %>
#[rustler::nif]
pub fn <%= typ_low %><%= bits %>_transpose(a: Ex<%= typ_upper %><%= bits %>Array2) -> Ex<%= typ_upper %><%= bits %>Array2 {
  let m = a.resource.0.clone().reversed_axes();
  Ex<%= typ_upper %><%= bits %>Array2::new(m)
}
<% end %>

// =========================================
// Real numbers
// =========================================
<%= for bits <- [64, 32], n_dim <- 1..6 do %>
// -----------------------------------------
// <%= n_dim %>D arrays
// -----------------------------------------
#[rustler::nif]
pub fn float<%= bits %>_array<%= n_dim %>_sum(a: ExFloat<%= bits %>Array<%= n_dim %>) -> f<%= bits %> {
  a.resource.0.sum()
}
<% end %>

// =========================================
// Complex numbers
// =========================================
<%= for bits <- [64, 32], n_dim <- 1..6 do %>
// -----------------------------------------
// <%= n_dim %>D arrays
// -----------------------------------------
#[rustler::nif]
pub fn complex<%= bits %>_array<%= n_dim %>_sum(a: ExComplex<%= bits %>Array<%= n_dim %>) -> ExComplex<%= bits %> {
  ExComplex<%= bits %>::new(a.resource.0.sum())
}
<% end %>